/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloWorld_H
#define HelloWorld_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "example_types.h"

namespace example {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloWorldIf {
 public:
  virtual ~HelloWorldIf() {}
  virtual void sayHello(std::string& _return, const std::string& name) = 0;
};

class HelloWorldIfFactory {
 public:
  typedef HelloWorldIf Handler;

  virtual ~HelloWorldIfFactory() {}

  virtual HelloWorldIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloWorldIf* /* handler */) = 0;
  };

class HelloWorldIfSingletonFactory : virtual public HelloWorldIfFactory {
 public:
  HelloWorldIfSingletonFactory(const ::std::shared_ptr<HelloWorldIf>& iface) : iface_(iface) {}
  virtual ~HelloWorldIfSingletonFactory() {}

  virtual HelloWorldIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(HelloWorldIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<HelloWorldIf> iface_;
};

class HelloWorldNull : virtual public HelloWorldIf {
 public:
  virtual ~HelloWorldNull() {}
  void sayHello(std::string& /* _return */, const std::string& /* name */) override {
    return;
  }
};

typedef struct _HelloWorld_sayHello_args__isset {
  _HelloWorld_sayHello_args__isset() : name(false) {}
  bool name :1;
} _HelloWorld_sayHello_args__isset;

class HelloWorld_sayHello_args {
 public:

  HelloWorld_sayHello_args(const HelloWorld_sayHello_args&);
  HelloWorld_sayHello_args& operator=(const HelloWorld_sayHello_args&);
  HelloWorld_sayHello_args() noexcept
                           : name() {
  }

  virtual ~HelloWorld_sayHello_args() noexcept;
  std::string name;

  _HelloWorld_sayHello_args__isset __isset;

  void __set_name(const std::string& val);

  bool operator == (const HelloWorld_sayHello_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const HelloWorld_sayHello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayHello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloWorld_sayHello_pargs {
 public:


  virtual ~HelloWorld_sayHello_pargs() noexcept;
  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayHello_result__isset {
  _HelloWorld_sayHello_result__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayHello_result__isset;

class HelloWorld_sayHello_result {
 public:

  HelloWorld_sayHello_result(const HelloWorld_sayHello_result&);
  HelloWorld_sayHello_result& operator=(const HelloWorld_sayHello_result&);
  HelloWorld_sayHello_result() noexcept
                             : success() {
  }

  virtual ~HelloWorld_sayHello_result() noexcept;
  std::string success;

  _HelloWorld_sayHello_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloWorld_sayHello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloWorld_sayHello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloWorld_sayHello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloWorld_sayHello_presult__isset {
  _HelloWorld_sayHello_presult__isset() : success(false) {}
  bool success :1;
} _HelloWorld_sayHello_presult__isset;

class HelloWorld_sayHello_presult {
 public:


  virtual ~HelloWorld_sayHello_presult() noexcept;
  std::string* success;

  _HelloWorld_sayHello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloWorldClient : virtual public HelloWorldIf {
 public:
  HelloWorldClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloWorldClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayHello(std::string& _return, const std::string& name) override;
  void send_sayHello(const std::string& name);
  void recv_sayHello(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloWorldProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<HelloWorldIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (HelloWorldProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sayHello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloWorldProcessor(::std::shared_ptr<HelloWorldIf> iface) :
    iface_(iface) {
    processMap_["sayHello"] = &HelloWorldProcessor::process_sayHello;
  }

  virtual ~HelloWorldProcessor() {}
};

class HelloWorldProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloWorldProcessorFactory(const ::std::shared_ptr< HelloWorldIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< HelloWorldIfFactory > handlerFactory_;
};

class HelloWorldMultiface : virtual public HelloWorldIf {
 public:
  HelloWorldMultiface(std::vector<std::shared_ptr<HelloWorldIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloWorldMultiface() {}
 protected:
  std::vector<std::shared_ptr<HelloWorldIf> > ifaces_;
  HelloWorldMultiface() {}
  void add(::std::shared_ptr<HelloWorldIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sayHello(std::string& _return, const std::string& name) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sayHello(_return, name);
    }
    ifaces_[i]->sayHello(_return, name);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloWorldConcurrentClient : virtual public HelloWorldIf {
 public:
  HelloWorldConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  HelloWorldConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayHello(std::string& _return, const std::string& name) override;
  int32_t send_sayHello(const std::string& name);
  void recv_sayHello(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
